### ISSUE TITLE
Fehler beim stoppen des Nodes

### ISSUE THREAD

**Issue by jw2702** [derklaro/reformcloud2#109]
Hallo,

ich habe mir ReformCloud erst heute installiert und es kommt leider ein Fehler im Node beim stoppen.
https://paste.reformcloud.systems/69l0Rki1L7
Diese Applications habe ich installiert: http://prntscr.com/sra0mc

Betriebssystem: Debian 10
Java-Version: 8
ReformCloud-Version: 2.2.2

Ich hoffe, dass ich alle nötigen Informationen geliefert habe.

**Comment by derklaro** [comment]
Fixed
